# HarborAI最简化发布流水线
name: Release Minimal

on:
  push:
    tags:
      - 'v*.*.*-test'
  workflow_dispatch:
    inputs:
      version:
        description: '发布版本号 (例如: v1.0.0-test)'
        required: true
        type: string

permissions:
  contents: write
  packages: write

env:
  PYTHON_VERSION: '3.10'

jobs:
  # 版本验证
  validate-version:
    name: 版本验证
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      is_prerelease: ${{ steps.version.outputs.is_prerelease }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 验证版本号
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
            IS_PRERELEASE="true"
          else
            VERSION="${GITHUB_REF#refs/tags/}"
            IS_PRERELEASE="true"
          fi
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "is_prerelease=$IS_PRERELEASE" >> $GITHUB_OUTPUT
          echo "✅ 版本号验证通过: $VERSION (预发布: $IS_PRERELEASE)"

  # 基本测试
  basic-test:
    name: 基本测试
    runs-on: ubuntu-latest
    needs: validate-version
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          
      - name: 安装基本依赖
        run: |
          python -m pip install --upgrade pip
          pip install build wheel
          
      - name: 验证包结构
        run: |
          python -c "import harborai; print('✅ HarborAI 包导入成功')"
          
      - name: 构建包
        run: |
          python -m build
          echo "✅ 包构建成功"

  # 创建发布
  create-release:
    name: 创建发布
    runs-on: ubuntu-latest
    needs: [validate-version, basic-test]
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 创建GitHub发布
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.validate-version.outputs.version }}
          release_name: HarborAI ${{ needs.validate-version.outputs.version }}
          body: |
            ## HarborAI ${{ needs.validate-version.outputs.version }}
            
            这是一个测试发布版本。
            
            ### 变更内容
            - 修复 GitHub Actions 发布流程
            - 简化发布配置
            
          draft: false
          prerelease: ${{ needs.validate-version.outputs.is_prerelease }}